name: 'Cloud Catcher '
favicon: null
layout_spectrum: 0.0585392
typography_spectrum: 0.2894737
title: Cloud Catcher Roastery - Specialty Coffee Roaster
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3d4b5'
    - '#17231f'
    - '#485932'
    - '#ffac00'
    - '#ff002d'
  brandStrength: 0.09183671
  lightness: 0.9179664
  saturation: 0.7717763
  rhythmicContrast: 0.02027412
purpose: []
